### ISSUE TITLE
rake test errors

### ISSUE THREAD

**Issue by pkarman** [PRX/audio_monster#2]
clean checkout yields this:

```
$ rake test
/home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1464: warning: already initialized constant Minitest
/home/karpet/.rvm/gems/ruby-2.0.0-p576/gems/minitest-5.5.1/lib/minitest/parallel.rb:1: warning: previous definition of Minitest was here
Run options: --seed 49257

# Running tests:

....E..EEF.E

Finished tests in 0.581796s, 20.6258 tests/s, 25.7823 assertions/s.

  1) Error:
test_0008_can slice a section out of an audio file(AudioMonster::Monster):
RuntimeError: File missing or 0 length: /home/karpet/pua/audio_monster/test/tmp/slice.wav
    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:946:in `check_local_file'
    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:581:in `slice_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:106:in `block (2 levels) in <top (required)>'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `block in _run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `_run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:789:in `block in autorun'

  2) Error:
test_0004_should encode an mp2 from a stereo wav(AudioMonster::Monster):
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:54:in `block (2 levels) in <top (required)>'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `block in _run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `_run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:789:in `block in autorun'

  3) Error:
test_0003_should encode an mp2 from a mono wav(AudioMonster::Monster):
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:39:in `block (2 levels) in <top (required)>'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `block in _run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `_run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:789:in `block in autorun'

  4) Failure:
test_0006_should get info for ogg file(AudioMonster::Monster) [/home/karpet/pua/audio_monster/test/monster_test.rb:74]:
Expected: 12
  Actual: 0

  5) Error:
test_0001_can create an mp2 from a wav file(AudioMonster::Monster):
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:13:in `block (2 levels) in <top (required)>'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `block in _run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `map'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:899:in `_run_suites'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/minitest/unit.rb:789:in `block in autorun'

12 tests, 15 assertions, 1 failures, 4 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0" "/home/karpet/.rvm/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)

```

**Comment by pkarman** [comment]
running 'bundle' and then 'bundle exec rake' yields slightly different errors:

```
$ bundle exec rake
Run options: --seed 16029

# Running:

.....EE.F.EE

Finished in 0.736681s, 16.2893 runs/s, 20.3616 assertions/s.

  1) Error:
AudioMonster::Monster#test_0004_should encode an mp2 from a stereo wav:
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:54:in `block (2 levels) in <top (required)>'


  2) Error:
AudioMonster::Monster#test_0003_should encode an mp2 from a mono wav:
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:39:in `block (2 levels) in <top (required)>'


  3) Failure:
AudioMonster::Monster#test_0006_should get info for ogg file [/home/karpet/pua/audio_monster/test/monster_test.rb:74]:
Expected: 12
  Actual: 0


  4) Error:
AudioMonster::Monster#test_0001_can create an mp2 from a wav file:
RuntimeError: encode_mp2_from_wav - twolame response on transcoding was not recognized as a success, 127
, nice: twolame: No such file or directory

    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:348:in `encode_mp2_from_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:13:in `block (2 levels) in <top (required)>'


  5) Error:
AudioMonster::Monster#test_0008_can slice a section out of an audio file:
RuntimeError: File missing or 0 length: /home/karpet/pua/audio_monster/test/tmp/slice.wav
    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:946:in `check_local_file'
    /home/karpet/pua/audio_monster/lib/audio_monster/monster.rb:581:in `slice_wav'
    /home/karpet/pua/audio_monster/test/monster_test.rb:106:in `block (2 levels) in <top (required)>'

12 runs, 15 assertions, 1 failures, 4 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/home/karpet/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.4.2/lib" "/home/karpet/.rvm/gems/ruby-2.0.0-p576/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/karpet/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/home/karpet/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by kookster** [comment]
I just did a clean clone from github, and all is well. Your issue is missing binaries.

It is noisy, so I don't do it by default as I used to, but you can check your binaries by doing the following,

1) Set the env var AUDIO_MONSTER_DEBUG to true, and it will check before running anything.

2) Run the binary check yourself

```
bundle console
> AudioMonster.check_binaries
```

**Comment by pkarman** [comment]
confirmed. I've opened #3 to reflect the necessary documentation.
